### ISSUE TITLE
Can you please add an option to disable tray icon?

### ISSUE THREAD

**Issue by butyoutried** [lordmulder/ClearClipboard#4]

**Comment by lordmulder** [comment]
Hello.

Why? The program is controlled entirely via the tray icon. So I think this is quite essential.

If you don't want to see the tray icon, then you can simply "hide" it by moving it (via drag & drop) to the [*overflow section*](https://support.microsoft.com/en-us/topic/guided-help-customize-the-notification-area-in-windows-7-508f3b7d-435d-2aea-d189-0d4b2d6eca13) 😏 

Regards.

**Comment by butyoutried** [comment]
Well, I exactly wanted to unclutter overflow section from tray icons which I don't need :)

Thanks anyway, love your program.

**Comment by lordmulder** [comment]
Try this version:
[ClearClipboard-TEST.2022-12-05.zip](https://github.com/lordmulder/ClearClipboard/files/10155473/ClearClipboard-TEST.2022-12-05.zip)

**Comment by butyoutried** [comment]
After setting HideNotificationIcon=1 in the config file, ClearClipboard works fine without any tray icon at all. Awesome, thank you!
