### ISSUE TITLE
Disabling Ditto detection error message?

### ISSUE THREAD

**Issue by lheydon** [lordmulder/ClearClipboard#5]
Hi **@lordmulder**,

Just discovered your excellent utility. I'm also running the awesome [Ditto](https://ditto-cp.sourceforge.io/) utility, however I have the Ditto setting **'Connect to Clipboard'** disabled. As such, entries selected from Ditto **are** sent to the clipboard, but things copied to the clipboard are **not** captured or retained by Ditto. That is, the process only happens in the one direction, and therefore creates no extra privacy issues for the user. As such, ClearClipboard's Ditto warning is not relevant to my situation and that of any other users using Ditto with **'Connect to Clipboard'** disabled.

Could you please either refine ClearClipboard's Ditto detection to recognise this and withold the error message or (probably more easily from your end) allow the user to ignore and supress that error message and run ClearClipboard in conjunction with Ditto uninterrupted by that error message?

Additionally, your Ditto error message contains reference to the README file for more information, however this file only has a single brief mention of Ditto (in the version history) and says significantly less about things than the error message dialog itself does.

Thanks in advance, please let me know if any aspect of this request needs clarification.

LH

![Screenshot 2024-11-28 154325](https://github.com/user-attachments/assets/70c093b3-d21e-4493-90ff-7620ef150f08)

![Screenshot 2024-11-28 154238](https://github.com/user-attachments/assets/c1d88018-1310-45ae-96d7-4f8d37a809d6)

![FireShot Capture 245 - Command Line Options · sabrogden_Ditto Wiki - github com](https://github.com/user-attachments/assets/4ec4882e-aca2-40cb-a470-bc94223887b1)

![Screenshot 2024-11-28 155646](https://github.com/user-attachments/assets/30905769-82ff-4e32-bc7c-1d27272cdf10)

**Comment by lheydon** [comment]
@lordmulder, bumping this issue thread thanks!

**Comment by lordmulder** [comment]
Hello.

You can set configuration option `DisableWarningMessages=1` in order to disable this warning message.

Regards.

**Comment by lheydon** [comment]
@lordmulder awesome, thanks.

**Comment by lheydon** [comment]
@lordmulder, awesome thanks.
